### ISSUE TITLE
Failed to activate the path package

### ISSUE THREAD

**Issue by camjc** [weskinner/path#1]
Run atom from terminal using command `atom --one`.
This puts atom into 1.0 preview mode.

I really love this package, especially relative path to me.

**Atom Version**: 0.199.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10
**Thrown From**: [path](https://github.com/weskinner/path) package, v0.4.1
### Stack Trace

Failed to activate the path package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/Cam/.atom/packages/path/lib/path.coffee:11:25)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:435:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:419:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:414:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:395:46)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-paths, v1.0.2
linter, v0.12.2
npm-autocomplete, v0.1.2
path, v0.4.1

# Dev
No dev packages
```

**Comment by camjc** [comment]
Now Path won't load in Atom at all. Any chance of an update or is this package abandoned? I really love using the 'relative path to me' feature.
